services:
- type: web
  name: qg-cms-frontend 
  env: node
  plan: starter plus
  buildCommand: cd qg-cms-front/ && yarn install && yarn run build
  startCommand: cd qg-cms-front/ && yarn start
  envVars:
  - key: NODE_ENV
    value: production
  - key: STRAPI_API_URL
    value: https://strapi-v5q5.onrender.com
  - key: NEXT_PUBLIC_STRAPI_API_URL
    value: https://strapi-v5q5.onrender.com  
